### PR TITLE
Reject All

### PR DESCRIPTION
**Pull request by qdcheng1**
Add Reject All feature for bulk reject. Modify the verity state to support reject all.

### CODE REVIEW

**Comment by Davidezrajay** [comment]
#113

**Comment by dadiorchen** [comment]
David, I tried your code, found some problem, it seems like when rejecting all operation, it would led to some disorder status, look below gif, when I rejected a tree, then tried to undo this operation, then I got a tree list with wrong order, looks like the order direction has been reversed, and I thought I met some other wrong case, try this: ( select a range, approve all, then undo it, then select another range, then reject all, check the result)
Untitled_ Jan 24 2020 10_40 AM

**Comment by dadiorchen** [comment]
@david-mike

**Comment by qdcheng1** [comment]
For the first case, it did cause wrong order. I found the same thing happen to Approve All as well. Since they call the same undo method. I need to fix the undo method. I did not get the other cases. Could you explain them in details?

**Pull request merged**
