### PR TITLE
Use treetracker admin

### PR DESCRIPTION
**Pull request by gloriaLVela**

### CODE REVIEW

**Comment by gloriaLVela** [comment]
Use treetracker-admin instead of treetracker-admin-apo

**Comment by ZavenArra** [comment]
@gloriaLVela This PR has several errors in it that cause the Dockerized development environment to not run.  Please test, fix, and re-submit!  Thanks!

**Comment by gloriaLVela** [comment]
App-working

@deepwinter  Thank you for the feedback. Please give me more details because it is working for me.

**Comment by ZavenArra** [comment]
HI @gloriaLVela treetracker-admin-api remains the correct name for the docker components that relate to the server side of this treetracker admin project.  You've renamed them to to treetracker-admin in several places, which is unfortunately not correct.  The updated you submitted to the ReadMe look right though, would you mind submitting those in a separate PR ?

**Comment by thiagodemellobueno** [comment]
@gloriaLVela - this build doesn't seem to work.
It's also not clear to me what problem this branch aims to resolve.

**Comment by gloriaLVela** [comment]
> @gloriaLVela - this build doesn't seem to work.
> It's also not clear to me what problem this branch aims to resolve.

The repository was renamed from treetracker-admin-api to treetracker-admin.
I posted that the files used treetracker-admin-api instead of treetracker-admin and got the request to modify the files to use treetracker-admin.

**Comment by ZavenArra** [comment]
The updates you submitted to the ReadMe look right though, would you mind submitting those in a separate PR ?

**Comment by gloriaLVela** [comment]
> The updates you submitted to the ReadMe look right though, would you mind submitting those in a separate PR ?

Ok.

**Comment by gloriaLVela** [comment]
> @gloriaLVela - this build doesn't seem to work.
> It's also not clear to me what problem this branch aims to resolve.

How can I undo the modifications to the docker-compose.yml and  nginx-reverse-proxy-admin.conf?

**Comment by ZavenArra** [comment]
@gloriaLVela Just create a new branch and re-apply the changes to the ReadMe there.

**Comment by gloriaLVela** [comment]
Are we going to modify the ReadMe file only?  Are the rest of the files are going to use treetracker-admin-api?

**Comment by ZavenArra** [comment]
Hi @gloriaLVela   We use the name 'treetracker-admin' for this repository, but the name 'treetracker-admin-api' in our build scripts to reference the api container in Docker.  There is no reason wholesale update everything using 'treetracker-admin-api.'  I tried to explain this above, but hopefully this makes things more clear.   I'm not sure what your skillset it, but if you are not familiar with Docker and how our setup is working then it's easy to break stuff by just apply find/replace.   The changes you made the to ReadMe look right though, could you please create a separate PR with those changes close this one out ?

**Comment by gloriaLVela** [comment]
> Hi @gloriaLVela We use the name 'treetracker-admin' for this repository, but the name 'treetracker-admin-api' in our build scripts to reference the api container in Docker. There is no reason wholesale update everything using 'treetracker-admin-api.' I tried to explain this above, but hopefully this makes things more clear. I'm not sure what your skillset it, but if you are not familiar with Docker and how our setup is working then it's easy to break stuff by just apply find/replace. The changes you made the to ReadMe look right though, could you please create a separate PR with those changes close this one out ?

I closed this one. Should I create a new PR even though the ReadMe file is in the repository?

**Comment by ZavenArra** [comment]
Yes, that is the workflow.

**Pull request closed without merging**
