### PR TITLE
Initial docker code

### PR DESCRIPTION
**Pull request by mckornfield**
Not initially working, but I believe it is a config issue.

### CODE REVIEW

**Comment by mckornfield** [comment]
@deepwinter Should be ready for review. Got it working locally now

**Comment by thiagodemellobueno** [comment]
@mckornfield - thanks for this, I'll try and give it a spin this evening and report back.

**Comment by mckornfield** [comment]
Yep no problem... I can work on it more if need be as well.

**Comment by mckornfield** [comment]
@thiagodemellobueno I would test it again, got it running this time by removing the scripts from the docker ignore.

**Pull request merged**
