### PR TITLE
ImageScrubber husk

### PR DESCRIPTION
**Pull request by thiagodemellobueno**

### CODE REVIEW

**Comment by thiagodemellobueno** [comment]
@deepwinter  - no need to merge yet, we can work it here til its a good "mvp feature"

**Comment by ZavenArra** [comment]
Great work @thiagodemellobueno !  Thanks for getting us to this point.  Merging now.

**Comment by quorth0n** [comment]
I notice the `Mark Inactive` button in the datatable was removed in this PR. Are we only going to have this feature in the ImageScrubber then? I will keep that in mind when finishing up #45 if so.

**Comment by ZavenArra** [comment]
@whirish I noticed this too and it's an error.  Please but that button back for now and submit a PR.  Thanks!

**Comment by thiagodemellobueno** [comment]
Probably a merge issue, apologies!

**Pull request merged**
