### PR TITLE
Fix non-working trees directory, improve app structure

### LINKED ISSUE #179: "Trees" menu item not working in production
left menu item "trees" seems to not respond.

### LINKED ISSUE #192: Broken link in menu
Steps to reproduce: 
navigate to http://localhost:8080/explorer
Open menu
Click on Trees button

Result:
Application will crash

Expected result:
Application wont crash

Screenshot 2020-05-16 at 12 12 22
Screenshot 2020-05-16 at 12 12 10

### PR DESCRIPTION
**Pull request by lukasbicus**
closes #179
closes #192
initial work on #198

In this PR I add React router, refactor app structure (little bit, needs to finish) and fix issue with not working item in menu.

### CODE REVIEW

**Comment by dadiorchen** [comment]
@LukasBicus This PR is too big! We can not do things in this way, please solve the problem one by one, too big PR brings higher risk in product. 
I need you to slow down the pace, and just be focus on a few points at a time!
Please understand, QC is important for us. 
We need your experience, thanks for doing work with so much enthusiasm, I thought the best way to use your skill is to help us with this issue: #183 it is pretty urgent for us and also a bit tricky. Can you do it? Is there any roadblock for you?

**Comment by lukasbicus** [comment]
> @LukasBicus This PR is too big! We can not do things in this way, please solve the problem one by one, too big PR brings higher risk in product.
> I need you to slow down the pace, and just be focus on a few points at a time!
> Please understand, QC is important for us.
> We need your experience, thanks for doing work with so much enthusiasm, I thought the best way to use your skill is to help us with this issue: #183 it is pretty urgent for us and also a bit tricky. Can you do it? Is there any roadblock for you?

@dadiorchen - actually yes. This table is in `TreeTable` component, which is in `Trees` components. And this is currently unreachable. If you try to navigate there, app crashes. You want from me to fix/remove update something, I can't even see. Of course I want to fix the issue with tables, but this is PR is kind of prerequisite.

This PR enables me to navigate to that table. I understand, it's big, but most changes are only running prettier and renaming js files to jsx files. I will try to reduce it little bit, but I'm afraid, it will stay middle-size.

**Comment by lukasbicus** [comment]
@dadiorchen - I did my best, I reduced size of PR by 1000 lines and synced it with master. I hope now it's acceptable. Once this is merged, #183 will be unblocked.

**Comment by dadiorchen** [comment]
There are too much difference, you almost changed all the files, it's hard to review you know. And you no need to re-format all the files, it's not necessary to do so. 
About the unreachable for #183, that's reasonable, I can solve it first to let you do the tickets. It just a simple bug that needs to be solved.

**Comment by dadiorchen** [comment]
Actually, it is this issue: #166

**Comment by dadiorchen** [comment]
I will close this one first, you can reserve all the code locally and commit them later,  let's solve these problems one by one.

**Pull request closed without merging**
